# Generated by Django 5.0.8 on 2024-09-17 07:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_lesson_number_course_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
