# Generated by Django 5.0.8 on 2024-09-17 08:59

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_tags_alter_course_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='courses/%Y/%m', validators=[courses.validators.file_size]),
        ),
    ]
