# Generated by Django 5.0.8 on 2024-09-26 16:51

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_video_lesson_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='courses/%Y/%m', validators=[courses.validators.file_size]),
        ),
    ]
