# Generated by Django 5.0.8 on 2024-09-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_video_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='url',
        ),
    ]
