"""
Django settings for courseapp project.

Generated by 'django-admin startproject' using Django 5.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4bl)oe$u0h$c!-*t9isaza9co#2e+ta&^vrz(zzt=!30y8(sw_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'courses.apps.CoursesConfig',
    'ckeditor',
    'ckeditor_uploader',
    "debug_toolbar",
    'rest_framework',
    'drf_yasg',
    'cloudinary',
    'oauth2_provider',
    'corsheaders',
]

CORS_ALLOW_ALL_ORIGINS = True

CLIENT_ID = 'wo6xNMHb2lvJL91do5WPM4h58kKxsHq070g2WlGi'
CLIENT_SECRET = 'yAAEJgn0zdF5VA9EbYpK3YnFYhkHZlBvVEkVC1fDywq9Sn9FSTXB3kDlUjwLDAkjfVVHLMkVEQaJSmlpFrx96ms9TTcSGCN54xdgfYRvyQn6pZXBm9weDMOvQgTpMvOI'

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000

import cloudinary

# Configuration
cloudinary.config(
    cloud_name="dzrgeifj0",
    api_key="262971611872386",
    api_secret="V_quhmkJmcfvx03ZSNdAlmuCuhk",  # Click 'View Credentials' below to copy your API secret
)

MEDIA_ROOT = '%s/courses/static/' % BASE_DIR

CKEDITOR_UPLOAD_PATH = "ckeditor/images/"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ALLOWED_HOSTS = ['127.0.0.1', 'localhost','192.168.56.1']

import pymysql

pymysql.install_as_MySQLdb()

ROOT_URLCONF = 'courseapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'courseapp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'coursesdb',
        'USER': 'root',
        'PASSWORD': 'Thao123',
        'HOST': ''  # mặc định localhost
    }
}

INTERNAL_IPS = [
    "127.0.0.1",
]

AUTH_USER_MODEL = 'courses.User'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MAILCHIMP_API_KEY = '1231f386e08b1f794e456ba3b9e9aef4-us14'
MAILCHIMP_LIST_ID = '3746e14607'
MAILCHIMP_SERVER_PREFIX = 'us14'
